"""Signed alert links — the Python half of the token scheme in api/_auth.js.

Every alert email carries two links the recipient owns: an unsubscribe link and
a preferences link. Both are minted here, in the GitHub Actions sender, and
both are verified over in Node by api/alerts.js. So the two implementations
have to agree byte-for-byte on the signature, forever.

    token = b64url(payload_json) + "." + b64url(HMAC-SHA256(payload_json_b64, AUTH_SECRET))

The subtle part is what is *not* required to match: the JSON encoding itself.
Verification re-HMACs the body string exactly as it arrived on the wire and
only then parses it, so Python's ``json.dumps`` spacing and JavaScript's
``JSON.stringify`` spacing can differ freely. Only the b64url alphabet, the
padding strip, and the single "." separator are load-bearing. test_alert_subs.py
pins that agreement against vectors generated by Node so a change to either
side fails a test instead of silently orphaning every unsubscribe link we have
ever mailed.

Fails CLOSED, same rule as the Node side: no AUTH_SECRET means sign() raises
rather than minting a link nobody can honour. An email that ships with a dead
unsubscribe link is a CAN-SPAM problem, not a cosmetic one.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
import time
from typing import Any
from urllib.parse import quote

# An unsubscribe link lives in a mailbox for as long as the mailbox does. It
# has to outlive any reasonable "I'll get to it later", so it is measured in
# years, not hours. The preferences link rides the same clock.
LINK_TTL_DAYS = 730


class NoSecret(RuntimeError):
    """AUTH_SECRET is absent — refuse to mint an unverifiable link."""


def _secret() -> str:
    s = os.environ.get("AUTH_SECRET", "")
    if not s:
        raise NoSecret(
            "AUTH_SECRET is not set. Every alert email must carry a working "
            "unsubscribe link, so we do not send at all rather than send one "
            "that cannot be verified."
        )
    return s


def b64url(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode().rstrip("=")


def from_b64url(s: str) -> bytes:
    pad = "=" * (-len(s) % 4)
    return base64.urlsafe_b64decode(s + pad)


def _mac(body: str, secret: str) -> str:
    return b64url(hmac.new(secret.encode(), body.encode(), hashlib.sha256).digest())


def sign(payload: dict[str, Any], secret: str | None = None) -> str:
    """payload -> "body.sig". Callers set payload["exp"] in ms since epoch."""
    key = secret if secret is not None else _secret()
    body = b64url(json.dumps(payload, separators=(",", ":")).encode())
    return body + "." + _mac(body, key)


def verify(token: str, secret: str | None = None) -> dict[str, Any] | None:
    """token -> payload, or None on tamper/expiry/missing secret.

    Present so the selfcheck can round-trip without a live Vercel deploy; the
    real verification path in production is api/_auth.js.
    """
    try:
        key = secret if secret is not None else _secret()
    except NoSecret:
        return None
    if not token or "." not in token:
        return None
    body, _, sig = token.rpartition(".")
    if not hmac.compare_digest(sig, _mac(body, key)):
        return None
    try:
        payload = json.loads(from_b64url(body).decode())
    except (ValueError, UnicodeDecodeError):
        return None
    if not isinstance(payload, dict):
        return None
    exp = payload.get("exp")
    if exp and time.time() * 1000 > exp:
        return None
    return payload


def _exp_ms(days: int = LINK_TTL_DAYS) -> int:
    return int((time.time() + days * 86400) * 1000)


def unsub_link(email: str, base: str = "https://sooth.bet",
               secret: str | None = None) -> str:
    """One-click unsubscribe URL for this address."""
    tok = sign({"t": "u", "e": email, "exp": _exp_ms()}, secret)
    return f"{base}/api/alerts?unsub={quote(tok, safe='')}"


def prefs_link(email: str, base: str = "https://sooth.bet",
               secret: str | None = None) -> str:
    """Deep link back to the alerts page with this address pre-filled.

    Distinct from unsubscribe on purpose: "this one is too noisy" and "never
    contact me again" are different requests, and collapsing them into one
    button is how a product loses subscribers it could have kept by letting
    them raise a threshold instead.
    """
    tok = sign({"t": "p", "e": email, "exp": _exp_ms()}, secret)
    return f"{base}/alerts?prefs={quote(tok, safe='')}"
