"""Tests for the alert subscriber list, the link tokens, and per-person sends.

Three failure modes are expensive enough to pin here:

1. **Mailing someone who did not ask.** Consent is the whole liability surface
   of an email product, and the ways to get it wrong are all quiet: a customer
   record with no opt-in flag, one that opted out, one confirmed for a kind
   they didn't pick.
2. **Mailing someone twice, or not at all, when a price moves.** The watermark
   is the only thing between us and either outcome, and it changed shape when
   subscribers gained their own thresholds.
3. **A dead unsubscribe link.** The token is minted in Python and verified in
   Node; if the two implementations drift, every link we have ever mailed
   breaks at once and there is no way to notice from the Python side alone.
   The vectors below were generated by api/_auth.js and are checked in.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from engine import alert_token, subscribers
from engine.alert_email import (RESEND_STEP, alert_key, for_recipient, load_sent,
                                mark, render, save_sent, select_new)

SECRET = "selfcheck-secret"


# --------------------------------------------------------------------------
# 1. consent: who is on the list
# --------------------------------------------------------------------------

def cust(email="a@b.com", **meta):
    return {"id": "cus_1", "email": email, "metadata": meta}


def test_only_a_confirmed_opt_in_is_on_the_list():
    ok = subscribers.from_customer(
        cust(sooth_alerts="1", sooth_kinds="seal,price", sooth_min_pts="2.5"))
    assert ok is not None and ok.email == "a@b.com"
    assert ok.kinds == {"seal", "price"} and ok.min_pts == 2.5


@pytest.mark.parametrize("meta", [
    {},                                                    # a plain customer
    {"sooth_kinds": "seal"},                               # flag never set
    {"sooth_alerts": "0", "sooth_kinds": "seal"},          # unsubscribed
    {"sooth_alerts": "1"},                                 # opted in to nothing
    {"sooth_alerts": "1", "sooth_kinds": ""},              # ...explicitly
    {"sooth_alerts": "1", "sooth_kinds": "nonsense"},      # only unknown kinds
    {"sooth_alerts": "true", "sooth_kinds": "seal"},       # not the sentinel
])
def test_anything_short_of_an_explicit_opt_in_is_not_a_subscriber(meta):
    """A Stripe customer is not a mailing list. Paying is not consent."""
    assert subscribers.from_customer(cust(**meta)) is None


def test_a_customer_with_no_email_is_never_a_subscriber():
    assert subscribers.from_customer(
        cust(email="", sooth_alerts="1", sooth_kinds="seal")) is None


def test_unsubscribing_wins_over_an_older_confirmation():
    """The most recent decision about an address is the one that counts."""
    old = cust(sooth_alerts="1", sooth_kinds="seal",
               sooth_confirmed_at="2026-01-01T00:00:00Z")
    assert subscribers.from_customer(old) is not None
    off = dict(old, metadata=dict(old["metadata"], sooth_alerts="0"))
    assert subscribers.from_customer(off) is None


def test_threshold_is_clamped_not_trusted():
    assert subscribers.clamp_min("2.5") == 2.5
    assert subscribers.clamp_min(-99) == subscribers.MIN_FLOOR
    assert subscribers.clamp_min(10_000) == subscribers.MIN_CEIL
    assert subscribers.clamp_min("nonsense") == subscribers.DEFAULT_MIN
    assert subscribers.clamp_min(None) == subscribers.DEFAULT_MIN
    assert subscribers.clamp_min(float("nan")) == subscribers.DEFAULT_MIN


def test_wants_respects_both_the_kind_and_the_threshold():
    s = subscribers.Subscriber("a@b.com", frozenset({"price", "seal"}), 3.0)
    assert s.wants("price", 3.0) and s.wants("price", 9.9)
    assert not s.wants("price", 2.9)
    assert not s.wants("graded"), "a kind not chosen is never sent"
    # a threshold is meaningless for an event with no magnitude
    assert s.wants("seal") and s.wants("seal", 0.0)


def test_the_run_floor_is_the_lowest_anyone_asked_for():
    subs = [subscribers.Subscriber("a@b.com", frozenset({"price"}), 4.0),
            subscribers.Subscriber("b@b.com", frozenset({"price"}), 1.5)]
    assert subscribers.floor_for(subs) == 1.5
    # someone who wants no price alerts cannot drag the floor down
    seal_only = subscribers.Subscriber("c@b.com", frozenset({"seal"}), 1.5)
    assert subscribers.floor_for([subs[0], seal_only]) == 4.0
    assert subscribers.floor_for([]) == subscribers.MIN_FLOOR


# --------------------------------------------------------------------------
# 2. the watermark: exactly once, per magnitude
# --------------------------------------------------------------------------

def div(event="g1", pts=3.0, book="FD"):
    return {"kind": "divergence", "event_id": event, "market": "moneyline",
            "selection": "A", "line": None, "book": book, "move_pts": pts,
            "sport": "nfl", "away": "X", "home": "Y", "detail": "d",
            "kickoff": "2099-01-01T00:00:00+00:00"}


def test_an_alert_already_sent_at_this_size_does_not_repeat():
    scan = {"divergence": [div(pts=3.0)]}
    assert select_new(scan, {alert_key(div()): 3.0}, 1.5) == []


def test_a_divergence_that_grows_past_the_step_speaks_again():
    """Otherwise a 2pt gap that becomes a 6pt gap never reaches the person
    who only wanted to hear about 4pt gaps."""
    scan = {"divergence": [div(pts=2.0 + RESEND_STEP)]}
    assert len(select_new(scan, {alert_key(div()): 2.0}, 1.5)) == 1


def test_a_small_reprice_is_the_same_opportunity():
    scan = {"divergence": [div(pts=2.0 + RESEND_STEP / 2)]}
    assert select_new(scan, {alert_key(div()): 2.0}, 1.5) == []


def test_one_batch_becomes_different_emails_per_threshold():
    new = select_new({"divergence": [div("g1", 5.0), div("g2", 2.0)]}, {}, 1.5)
    quiet = subscribers.Subscriber("q@x.com", frozenset({"price"}), 4.0)
    eager = subscribers.Subscriber("e@x.com", frozenset({"price"}), 1.5)
    assert [a["event_id"] for a in for_recipient(new, quiet, {})] == ["g1"]
    assert [a["event_id"] for a in for_recipient(new, eager, {})] == ["g1", "g2"]


def test_watermark_round_trips_magnitudes(tmp_path):
    p = str(tmp_path / "wm.json")
    save_sent(mark({}, [div("g1", 3.0), div("g2", 1.75)]), p)
    back = load_sent(p)
    assert back[alert_key(div("g1"))] == 3.0
    assert back[alert_key(div("g2"))] == 1.75


def test_mark_keeps_the_loudest_send_not_the_latest(tmp_path):
    sent = mark({}, [div("g1", 5.0)])
    sent = mark(sent, [div("g1", 2.0)])
    assert sent[alert_key(div("g1"))] == 5.0, \
        "dropping to the quieter value would re-fire the loud one"


def test_the_old_list_watermark_upgrades_without_remailing_everything(tmp_path):
    """The format changed from a list of keys to key -> magnitude.

    Every key already in the old file has been sent; none of them carries a
    magnitude. Restoring them at 0 would treat the entire back-catalogue as
    unsent and mail it to the first subscriber in one go.
    """
    p = tmp_path / "wm.json"
    p.write_text(json.dumps({"keys": [alert_key(div("g1"))]}))
    sent = load_sent(str(p))
    assert sent[alert_key(div("g1"))] == float("inf")
    assert select_new({"divergence": [div("g1", 99.0)]}, sent, 1.5) == []
    # and it survives being written back out
    save_sent(sent, str(p))
    assert load_sent(str(p))[alert_key(div("g1"))] == float("inf")


def test_a_missing_or_corrupt_watermark_is_empty_not_fatal(tmp_path):
    assert load_sent(str(tmp_path / "nope.json")) == {}
    bad = tmp_path / "bad.json"
    bad.write_text("{not json")
    assert load_sent(str(bad)) == {}


# --------------------------------------------------------------------------
# 3. links: Python mints them, Node verifies them
# --------------------------------------------------------------------------

def test_every_rendered_email_carries_an_unsubscribe():
    new = [div("g1", 3.0)]
    unsub = alert_token.unsub_link("a@b.com", "https://sooth.bet", SECRET)
    prefs = alert_token.prefs_link("a@b.com", "https://sooth.bet", SECRET)
    _, html, text = render(new, unsub, prefs)
    for body in (html, text):
        assert "unsub=" in body
        assert "1-800-522-4700" in body


def test_the_sender_refuses_to_mail_without_a_working_opt_out():
    from engine import mailer
    assert mailer.send("k", "a@b.com", "s", "<p>x</p>", "x", "") is False


def test_signing_without_a_secret_raises_rather_than_minting_a_dead_link(monkeypatch):
    monkeypatch.delenv("AUTH_SECRET", raising=False)
    with pytest.raises(alert_token.NoSecret):
        alert_token.unsub_link("a@b.com")


def test_tokens_round_trip_and_reject_tampering():
    tok = alert_token.sign({"t": "u", "e": "a@b.com", "exp": 4102444800000}, SECRET)
    assert alert_token.verify(tok, SECRET)["e"] == "a@b.com"
    assert alert_token.verify(tok[:-2] + "zz", SECRET) is None
    assert alert_token.verify("garbage", SECRET) is None
    assert alert_token.verify("", SECRET) is None
    expired = alert_token.sign({"t": "u", "e": "a@b.com", "exp": 1}, SECRET)
    assert alert_token.verify(expired, SECRET) is None
    assert alert_token.verify(tok, "a-different-secret") is None


# Generated by api/_auth.js under AUTH_SECRET="selfcheck-secret". If this ever
# fails, the two halves of the link scheme have drifted and every unsubscribe
# link already sitting in someone's mailbox has stopped working.
NODE_VECTOR = (
    "eyJ0IjoidSIsImUiOiJhQGIuY29tIiwiZXhwIjo0MTAyNDQ0ODAwMDAwfQ"
    ".2nI7J2WSlZkoI6H5PjNogX1SlPbl0kEibj7Uetjpep0"
)


def test_python_matches_the_node_signature_byte_for_byte():
    assert alert_token.sign(
        {"t": "u", "e": "a@b.com", "exp": 4102444800000}, SECRET) == NODE_VECTOR
    assert alert_token.verify(NODE_VECTOR, SECRET) == {
        "t": "u", "e": "a@b.com", "exp": 4102444800000}


def test_node_verifies_a_link_python_just_minted():
    """The check that actually matters, run against the real Node module."""
    tok = alert_token.sign({"t": "u", "e": "live@x.com", "exp": 4102444800000},
                           SECRET)
    root = Path(__file__).resolve().parents[1]
    script = (
        'process.env.AUTH_SECRET=%s;'
        'const a=require(%s);'
        'const p=a.verify(%s);'
        'process.stdout.write(JSON.stringify(p));'
        % (json.dumps(SECRET), json.dumps(str(root / "api" / "_auth.js")),
           json.dumps(tok))
    )
    try:
        out = subprocess.run(["node", "-e", script], capture_output=True,
                             text=True, timeout=30, check=True).stdout
    except (FileNotFoundError, subprocess.SubprocessError) as e:
        pytest.skip(f"node unavailable: {e}")
    assert json.loads(out) == {"t": "u", "e": "live@x.com", "exp": 4102444800000}


# ---------------------------------------------------------------------------
# The watchlist format has two implementations — engine/subscribers.py writes
# and reads it, api/alerts.js writes it from the browser — and they must agree
# forever. A drift here does not throw: it silently drops teams from somebody's
# list, and the only symptom is an email that never arrives.

TEAM_VECTORS = [
    "nba:NYK,nfl:BUF",
    "nba:nyk,NFL:buf",          # case is repaired, not rejected
    "nba:NYK,nba:NYK",          # deduped
    "NYK",                      # unscoped: which league's NYK?
    "nba:",                     # no team named
    "nba:TOOLONG",              # not an abbreviation
    "basketball:NYK",           # sport too long
    "nba:N Y",                  # spaces are not abbreviations
    " nfl:BUF , nba:NYK ",      # whitespace around entries
    "",
    ",,,",
    "nba:NYK,junk,nfl:BUF",     # one bad entry does not poison the rest
    ",".join(f"nba:T{100 + i}" for i in range(90)),   # past Stripe's 500 cap
]


def test_python_and_node_agree_on_the_watchlist_format():
    root = Path(__file__).resolve().parents[1]
    script = (
        'const V=require(%s)._internals;'
        'process.stdout.write(JSON.stringify('
        '  %s.map(s => V.cleanTeams(s).join(","))));'
        % (json.dumps(str(root / "api" / "alerts.js")), json.dumps(TEAM_VECTORS))
    )
    try:
        out = subprocess.run(["node", "-e", script], capture_output=True,
                             text=True, timeout=30, check=True).stdout
    except (FileNotFoundError, subprocess.SubprocessError) as e:
        pytest.skip(f"node unavailable: {e}")
    node = json.loads(out)
    py = [subscribers.serialise_teams(subscribers.parse_teams(v))
          for v in TEAM_VECTORS]
    assert node == py


def test_a_watchlist_never_exceeds_the_stripe_metadata_cap():
    big = [f"nba:T{100 + i}" for i in range(200)]
    stored = subscribers.serialise_teams(big)
    assert len(stored) <= subscribers.TEAMS_MAX_BYTES
    # truncation is from the SORTED list, so the same watchlist always stores
    # the same subset rather than a new arbitrary one on every write
    kept = stored.split(",")
    assert kept == sorted(big)[:len(kept)]
    assert subscribers.parse_teams(stored) == frozenset(kept)


def test_game_alerts_need_somebody_to_follow():
    s = subscribers.Subscriber("a@b.com", frozenset({"game"}), 2.5, frozenset())
    assert not s.wants("game"), "an empty watchlist matches nothing, not everything"
    assert not s.watches("nba:NYK")
    t = subscribers.Subscriber("a@b.com", frozenset({"game"}), 2.5,
                               frozenset({"nba:NYK"}))
    assert t.wants("game") and t.watches("nfl:BUF", "nba:NYK")
    assert not t.watches("nfl:BUF"), "only the teams they actually picked"
